force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>The Scheduling object is used to manage and track the appointments or activities that are planned for clients.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the reservation (e.g., Pending, Confirmed, Canceled). This field tracks the state of the appointment.&quot;</description>
    <inlineHelpText>Indica el estado actual de la reserva</inlineHelpText>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Programado</label>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
                <label>En espera de pago</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Completado</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test/TestCancelIncompleteScheduling.cls
@isTest
private class TestCancelIncompleteScheduling {

    // Test para asegurarse de que el batch funcione correctamente
    @isTest
    static void testCancelIncompleteScheduling() {
        Appointment__c appointment1 = new Appointment__c(Status__c = 'New');
        // Appointment__c appointment2 = new Appointment__c(Status__c = 'Scheduled');
        Appointment__c appointment3 = new Appointment__c(Status__c = 'Completed'); 
        insert new List<Appointment__c>{appointment1, appointment3};

        List<Appointment__c> appointmentsBefore = [SELECT Id, Status__c FROM Appointment__c];

        System.assertEquals(appointmentsBefore.size(), 2);
        System.assert(appointmentsBefore[0].Status__c == 'New');
        //System.assert(appointmentsBefore[1].Status__c == 'Scheduled');
        System.assert(appointmentsBefore[1].Status__c == 'Completed');

        Test.startTest();
        CancelIncompleteScheduling batch = new CancelIncompleteScheduling();
        Database.executeBatch(batch, 100); 
        Test.stopTest();

        List<Appointment__c> appointmentsAfter = [SELECT Id, Status__c FROM Appointment__c WHERE Id IN :appointmentsBefore];

        for (Appointment__c appointment : appointmentsAfter) {
            if (appointment.Status__c == 'New') {
                System.assertEquals(appointment.Status__c, 'Canceled', 'El estado de la cita debería ser "Canceled".');
            }
        }

        System.assertEquals(appointmentsAfter[1].Status__c, 'Completed', 'El estado de la cita "Completed" no debe cambiar.');
    }
}