force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>The Scheduling object is used to manage and track the appointments or activities that are planned for clients.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Scheduling_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduling_Date__c</fullName>
    <description>The date when the scheduling is planned to take place.</description>
    <inlineHelpText>Ingrese la fecha de reservación</inlineHelpText>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the reservation (e.g., Pending, Confirmed, Canceled). This field tracks the state of the appointment.&quot;</description>
    <inlineHelpText>Indica el estado actual de la reserva</inlineHelpText>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Programado</label>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
                <label>En espera de pago</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Completado</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Total_Duration__c.field-meta.xml
<CustomField>
    <fullName>Total_Duration__c</fullName>
    <description>The total duration of the scheduling, calculated by summing the durations of all related items in the scheduling.</description>
    <inlineHelpText>Duración total de la reserva</inlineHelpText>
    <label>Duración total</label>
    <summarizedField>Appointment_Item__c.Duration__c</summarizedField>
    <summaryForeignKey>Appointment_Item__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <description>The total value of the scheduling, calculated by summing the costs of all related items in the scheduling.</description>
    <inlineHelpText>Valor total de la reserva</inlineHelpText>
    <label>Valor total</label>
    <summarizedField>Appointment_Item__c.Value__c</summarizedField>
    <summaryForeignKey>Appointment_Item__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/Appointment_Item__c.object-meta.xml
<CustomObject>
    <description>Represents an individual item within a schedule.</description>
    <label>Appointment Item</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Item__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The duration of the schedule item in hours or minutes</description>
    <inlineHelpText>Enter the estimated duration for the procedure or service</inlineHelpText>
    <label>Duración</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the procedure related to this schedule item</description>
    <inlineHelpText>Este campo se vincula un procedimiento que está asociado con el elemento en el cronograma.</inlineHelpText>
    <label>Procedimiento</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Ítems de la programación</relationshipLabel>
    <relationshipName>Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Professional__c.field-meta.xml
<CustomField>
    <fullName>Professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the professional assigned to the item</description>
    <inlineHelpText>This field links to the user who will be responsible for performing the procedure</inlineHelpText>
    <label>Profesional</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <description>Relates to the associated schedule for this item</description>
    <inlineHelpText>This field links the item to a specific schedule, allowing you to associate the item with a particular program</inlineHelpText>
    <label>Schedule</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Represents the status of the schedule item</description>
    <inlineHelpText>Select the current status of this item in the schedule</inlineHelpText>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Completado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The monetary value associated with the schedule item</description>
    <inlineHelpText>Ingrese el valor del procedimiento</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The duration of the procedure in minutes. This field represents the actual time required to complete the procedure.</description>
    <inlineHelpText>Enter the time duration of the procedure in minutes</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/test/TestAppointmentController.cls
@isTest
public class TestAppointmentController {
    
    @testSetup
    static void setup() {
        
        User professional1 = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        
        // Crear cita de prueba (Appointment)
        Appointment__c appointment = new Appointment__c(
            Scheduling_Date__c = Date.today(),
            Status__c = 'New'
        );
        insert appointment;
        
        // Crear procedimientos de prueba (Product2)
        Product2 procedure1 = new Product2(
            Name = 'Test Procedure 1', 
            IsTestModeForValidation__c = true, 
            IsActive = true
        );
        insert procedure1;
        
        // Crear ítems de cita (Appointment Items)
        Appointment_Item__c item1 = new Appointment_Item__c(
        	Schedule__c = appointment.Id,
        	Procedure__c = procedure1.Id,
        	Professional__c = professional1.Id,
        	Value__c = 50,
        	Duration__c = 20
        );
        insert item1;
        
        // Actualizar la cita para recalcular los campos de resumen
    	appointment = [SELECT Id, Total_Value__c, Total_Duration__c FROM Appointment__c WHERE Id = :appointment.Id];
    	update appointment;
    }
    
    @isTest
    static void testGetAppointmentDetails_Success() {
        // get Id of the appointment created in the setup method
        Appointment__c appointmentId = [SELECT Id FROM Appointment__c LIMIT 1];

        // Call the method to be tested
        Test.startTest();
        AppointmentController.AppointmentSummary result = AppointmentController.getAppointmentDetails(appointmentId.Id);
        Test.stopTest();
        
        // Validate the results
        System.assertNotEquals(result, null, 'Result should not be null');
        System.assertEquals(result.reservationDate, Date.today(), 'The reservation date should match');
        System.assertEquals(result.appointmentStatus, 'New', 'The appointment status should match');
        System.assertEquals(result.procedures[0].name, 'Test Procedure 1', 'The first procedure name should match');
    }
    
    @isTest
    static void testGetAppointmentDetails_NoProcedures() {
        // Create an appointment without related procedures
        Appointment__c appointment = new Appointment__c(
            Scheduling_Date__c = Date.today(),
        	Status__c = 'New'
        );
        insert appointment;
        
        // Call the method to be tested
        Test.startTest();
        AppointmentController.AppointmentSummary result = AppointmentController.getAppointmentDetails(appointment.Id);
        Test.stopTest();
        
        // Validate that no procedures are returned
        System.assertNotEquals(result, null, 'Result should not be null');
        System.assertEquals(result.procedures.size(), 0, 'There should be no procedures');
    }
}