force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>The Scheduling object is used to manage and track the appointments or activities that are planned for clients.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the reservation (e.g., Pending, Confirmed, Canceled). This field tracks the state of the appointment.&quot;</description>
    <inlineHelpText>Indica el estado actual de la reserva</inlineHelpText>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Programado</label>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
                <label>En espera de pago</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Completado</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/Appointment_Item__c.object-meta.xml
<CustomObject>
    <description>Represents an individual item within a schedule.</description>
    <label>Appointment Item</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Item__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The duration of the schedule item in hours or minutes</description>
    <inlineHelpText>Enter the estimated duration for the procedure or service</inlineHelpText>
    <label>Duración</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the procedure related to this schedule item</description>
    <inlineHelpText>Este campo se vincula un procedimiento que está asociado con el elemento en el cronograma.</inlineHelpText>
    <label>Procedimiento</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Ítems de la programación</relationshipLabel>
    <relationshipName>Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <description>Relates to the associated schedule for this item</description>
    <inlineHelpText>This field links the item to a specific schedule, allowing you to associate the item with a particular program</inlineHelpText>
    <label>Schedule</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Represents the status of the schedule item</description>
    <inlineHelpText>Select the current status of this item in the schedule</inlineHelpText>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Completado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>The cost of the procedure. This field represents the financial charge per procedure.</description>
    <inlineHelpText>Ingrese el valor del procedimiento</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The duration of the procedure in minutes. This field represents the actual time required to complete the procedure.</description>
    <inlineHelpText>Enter the time duration of the procedure in minutes</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/test/TestUpdateAppointmentStatusPending.cls
@isTest
public class TestUpdateAppointmentStatusPending {
    
    @isTest
    static void testUpdateStatusToPendingPayment() {

        Product2 testProcedure = new Product2(
            Name = 'Procedimiento A',
            Duration__c = 60,
            Cost__c = 100,
            IsTestModeForValidation__c = true, 
            IsActive = true
        );
        insert testProcedure;

        // Crear datos de prueba para Appointment__c
        Appointment__c reservation = new Appointment__c(Status__c = 'New');
        insert reservation;
        
        // Crear datos de prueba para Appointment_Item__c
        Appointment_Item__c item1 = new Appointment_Item__c(Schedule__c = reservation.Id, Procedure__c = testProcedure.Id,  Status__c = 'New');
        Appointment_Item__c item2 = new Appointment_Item__c(Schedule__c = reservation.Id, Procedure__c = testProcedure.Id, Status__c = 'New');
        insert new List<Appointment_Item__c>{item1, item2};

        // Actualizar los Appointment_Item__c a 'Completed'
        item1.Status__c = 'Completed';
        item2.Status__c = 'Completed';
        update new List<Appointment_Item__c>{item1, item2};
        
        // Verificar que el estado de la reserva se actualiza a 'Pending Payment'
        Appointment__c updatedReservation = [SELECT Status__c FROM Appointment__c WHERE Id = :reservation.Id];
        System.assertEquals('Pending Payment', updatedReservation.Status__c, 'El estado de la reserva debe ser "Pending Payment"');
    }

    // Test donde no todos los Appointment_Item__c están completos, por lo que no se debe actualizar el estado de la reserva
    @isTest
    static void testNotAllItemsCompleted() {
        // Crear datos de prueba para Appointment__c
        Product2 testProcedure = new Product2(
            Name = 'Procedimiento A',
            Duration__c = 60,
            Cost__c = 100,
            IsTestModeForValidation__c = true, 
            IsActive = true
        );
        insert testProcedure;

        // Crear datos de prueba para Appointment__c
        Appointment__c reservation = new Appointment__c(Status__c = 'New');
        insert reservation;
        
        // Crear datos de prueba para Appointment_Item__c
        Appointment_Item__c item1 = new Appointment_Item__c(Schedule__c = reservation.Id, Procedure__c = testProcedure.Id,  Status__c = 'New');
        Appointment_Item__c item2 = new Appointment_Item__c(Schedule__c = reservation.Id, Procedure__c = testProcedure.Id, Status__c = 'New');
        insert new List<Appointment_Item__c>{item1, item2};

        // Actualizar solo un Appointment_Item__c a 'Completed'
        item1.Status__c = 'Completed';
        update new List<Appointment_Item__c>{item1};

        // Verificar que el estado de la reserva no cambia
        Appointment__c updatedReservation = [SELECT Status__c FROM Appointment__c WHERE Id = :reservation.Id];
        System.assertEquals('New', updatedReservation.Status__c, 'El estado de la reserva no debe cambiar porque no todos los elementos están completos');
    }

    // Test cuando no se actualizan Appointment_Item__c
    @isTest
    static void testNoAppointmentItemsUpdated() {
         // Crear datos de prueba para Appointment__c
        Product2 testProcedure = new Product2(
            Name = 'Procedimiento A',
            Duration__c = 60,
            Cost__c = 100,
            IsTestModeForValidation__c = true, 
            IsActive = true
        );
        insert testProcedure;

        // Crear datos de prueba para Appointment__c
        Appointment__c reservation = new Appointment__c(Status__c = 'New');
        insert reservation;
        
        // Crear datos de prueba para Appointment_Item__c
        Appointment_Item__c item1 = new Appointment_Item__c(Schedule__c = reservation.Id, Procedure__c = testProcedure.Id,  Status__c = 'New');
        Appointment_Item__c item2 = new Appointment_Item__c(Schedule__c = reservation.Id, Procedure__c = testProcedure.Id, Status__c = 'New');
        insert new List<Appointment_Item__c>{item1, item2};

        // No actualizamos nada, solo verificamos que el trigger no ejecute cambios innecesarios
        Test.startTest();
        update new List<Appointment_Item__c>{};
        Test.stopTest();
        
        // Verificar que el estado de la reserva no cambia
        Appointment__c updatedReservation = [SELECT Status__c FROM Appointment__c WHERE Id = :reservation.Id];
        System.assertEquals('New', updatedReservation.Status__c, 'El estado de la reserva no debe cambiar ya que no se ha realizado ninguna actualización en los elementos');
    }
    
}