force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>The Scheduling object is used to manage and track the appointments or activities that are planned for clients.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the reservation (e.g., Pending, Confirmed, Canceled). This field tracks the state of the appointment.&quot;</description>
    <inlineHelpText>Indica el estado actual de la reserva</inlineHelpText>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Programado</label>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
                <label>En espera de pago</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Completado</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelIncompleteScheduling.cls
public class CancelIncompleteScheduling implements Database.Batchable<sObject> {


    public Iterable<Appointment__c> start(Database.BatchableContext context) {
        return [SELECT Id, Status__c FROM Appointment__c WHERE Status__c IN ('New', 'Scheduled')];
    }

    public void execute(Database.BatchableContext context, List<Appointment__c> scope) {
        List<Appointment__c> appointments = new List<Appointment__c>();
        for (Appointment__c appointment : scope) {
            appointment.Status__c = 'Canceled';
            appointments.add(appointment);
        }
        update appointments;
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Proceso de cancelación de tareas completado');
    }
}